### ISSUE TITLE
Mojolicious 6.x fix

### ISSUE THREAD

**Issue by merrilymeredith** [chromatic/Mojolicious-Plugin-UnicodeNormalize#2]
Hi, there's just a minor change required for a method that's been renamed:

from
`$c->req->params->params`

to
`$c->req->params->pairs`

**Comment by akarelas** [comment]
MetaCPAN says the module's bug-submission page is https://rt.cpan.org/Public/Dist/Display.html?Name=Mojolicious-Plugin-UnicodeNormalize

Perhaps you should try there.

:camel:

**Comment by chromatic** [comment]
I uploaded 1.20150802 to the CPAN just now with this fix and a dependency on Mojolicious 6.0. Thanks for the report!
